aws:
  region: eu-west-1

okta:
  organization: dev-203763
  aws_app:
    iam_user: OktaSSOUser
    label: Amazon Web Services

grant_types:
  query:
  - SELECT
  cru:
  - SELECT
  - UPDATE
  - INSERT
  crud:
  - SELECT
  - UPDATE
  - INSERT
  - DELETE

master_password_defaults:
  "([a-z][a-z0-9-]+)": ssm:\1.master_password
